<a href="https://colab.research.google.com/github/ananyaa06/AI_Portfolio_Project/blob/main/AI4ALL_code_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
dataset = pd.read_csv('data.csv')


In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le_count = 0
for col in dataset.columns[1:]:
    if dataset[col].dtype == 'object':
        if len(list(dataset[col].unique())) <= 2:
            le.fit(dataset[col])
            dataset[col] = le.transform(dataset[col])
            le_count += 1
print('{} columns were label encoded.'.format(le_count))

0 columns were label encoded.


In [44]:
dataset.head()

e_cblp  e_cp  e_cparhdr  e_maxalloc  e_sp  e_lfanew  NumberOfSections  \
0     144     3          4       65535   184       256                 4   
1     144     3          4       65535   184       184                 4   
2     144     3          4       65535   184       272                 5   
3     144     3          4       65535   184       184                 1   
4     144     3          4       65535   184       224                 5   

   CreationYear  FH_char0  FH_char1  ...  sus_sections  non_sus_sections  \
0             1         0         1  ...             1                 3   
1             1         0         1  ...             1                 3   
2             1         0         1  ...             1                 4   
3             1         0         1  ...             0                 1   
4             1         0         1  ...             1                 4   

   packer  packer_type    E_text    E_data  filesize    E_file  fileinfo  \
0       0     NoPacker  6.603616  5.443362   1181520  6.627552         1   
1       0     NoPacker  5.205926  2.123522      7680  5.318221         0   
2       0     NoPacker  6.238000  3.380859     57872  6.507758         1   
3       0     NoPacker  0.000000  0.000000     95616  4.575092         1   
4       0     NoPacker  6.355626  0.702621     48128  5.545531         1   

   class  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 70 columns]

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct_count = 0
for col in dataset.columns[1:]:
    if dataset[col].dtype == 'object':
        if len(list(dataset[col].unique())) >= 2:
          dataset = pd.concat([dataset,pd.get_dummies(dataset[col], prefix=col)], axis=1)
          dataset.drop([col],axis=1, inplace=True)
          ct_count += 1
print('{} columns were label encoded.'.format(ct_count))


1 columns were label encoded.


In [46]:
dataset.head()

e_cblp  e_cp  e_cparhdr  e_maxalloc  e_sp  e_lfanew  NumberOfSections  \
0     144     3          4       65535   184       256                 4   
1     144     3          4       65535   184       184                 4   
2     144     3          4       65535   184       272                 5   
3     144     3          4       65535   184       184                 1   
4     144     3          4       65535   184       224                 5   

   CreationYear  FH_char0  FH_char1  ...  packer_type_UPXProtectorv10x2  \
0             1         0         1  ...                              0   
1             1         0         1  ...                              0   
2             1         0         1  ...                              0   
3             1         0         1  ...                              0   
4             1         0         1  ...                              0   

   packer_type_UPXV200V290MarkusOberhumerLaszloMolnarJohnReiser  \
0                                                  0              
1                                                  0              
2                                                  0              
3                                                  0              
4                                                  0              

   packer_type_UPXv20MarkusLaszloReiser  packer_type_Upackv039finalDwing  \
0                                     0                                0   
1                                     0                                0   
2                                     0                                0   
3                                     0                                0   
4                                     0                                0   

   packer_type_VideoLanClient  packer_type_WinZip32bitSFXv8xmodule  \
0                           0                                    0   
1                           0                                    0   
2                           0                                    0   
3                           0                                    0   
4                           0                                    0   

   packer_type_WiseInstallerStub  packer_type_XtremeProtectorv105  \
0                              0                                0   
1                              0                                0   
2                              0                                0   
3                              0                                0   
4                              0                                0   

   packer_type_nSpackV2xLiuXingPing  packer_type_tElock09910privatetE  
0                                 0                                 0  
1                                 0                                 0  
2                                 0                                 0  
3                                 0                                 0  
4                                 0                                 0  

[5 rows x 109 columns]

In [47]:

dataset = dataset.dropna(axis=0)


In [48]:

dataset.head()

e_cblp  e_cp  e_cparhdr  e_maxalloc  e_sp  e_lfanew  NumberOfSections  \
0     144     3          4       65535   184       256                 4   
1     144     3          4       65535   184       184                 4   
2     144     3          4       65535   184       272                 5   
3     144     3          4       65535   184       184                 1   
4     144     3          4       65535   184       224                 5   

   CreationYear  FH_char0  FH_char1  ...  packer_type_UPXProtectorv10x2  \
0             1         0         1  ...                              0   
1             1         0         1  ...                              0   
2             1         0         1  ...                              0   
3             1         0         1  ...                              0   
4             1         0         1  ...                              0   

   packer_type_UPXV200V290MarkusOberhumerLaszloMolnarJohnReiser  \
0                                                  0              
1                                                  0              
2                                                  0              
3                                                  0              
4                                                  0              

   packer_type_UPXv20MarkusLaszloReiser  packer_type_Upackv039finalDwing  \
0                                     0                                0   
1                                     0                                0   
2                                     0                                0   
3                                     0                                0   
4                                     0                                0   

   packer_type_VideoLanClient  packer_type_WinZip32bitSFXv8xmodule  \
0                           0                                    0   
1                           0                                    0   
2                           0                                    0   
3                           0                                    0   
4                           0                                    0   

   packer_type_WiseInstallerStub  packer_type_XtremeProtectorv105  \
0                              0                                0   
1                              0                                0   
2                              0                                0   
3                              0                                0   
4                              0                                0   

   packer_type_nSpackV2xLiuXingPing  packer_type_tElock09910privatetE  
0                                 0                                 0  
1                                 0                                 0  
2                                 0                                 0  
3                                 0                                 0  
4                                 0                                 0  

[5 rows x 109 columns]

In [49]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Naive Bayes

In [59]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

Kernel SVM

In [60]:
from sklearn.svm import SVC
kernel = SVC(kernel = 'rbf', random_state = 0)
kernel.fit(X_train, y_train)

SVC(random_state=0)

Random Forest Classifier

In [61]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score

def display_cm(model):
  y_pred = model.predict(X_test)
  cm = confusion_matrix(y_test, y_pred)
  print(cm)
  print(accuracy_score(y_test, y_pred))
  

In [68]:
print('K-Means Results')
display_cm(nb)
print('Kernel SVM Results')
display_cm(kernel)
print('K-Means Results')
display_cm(rfc)

K-Means Results
[[1302    0]
 [   0    1]]
1.0
Kernel SVM Results
[[1302    0]
 [   1    0]]
0.9992325402916347
K-Means Results
[[1302    0]
 [   1    0]]
0.9992325402916347
